sudo: required
services:
  - docker

cache:
    directories:
     - $HOME/.cache

language: cpp
compiler:
  - clang

os:
  - linux
  - osx

env:
    matrix:
      - OS=ubuntu DIST=trusty
      - OS=ubuntu DIST=precise
      - OS=el DIST=6
      - OS=el DIST=7
os: osx
before_install:
  - git submodule update --init
  - git clone https://github.com/packpack/packpack.git packpack

before_script:
  - cmake .
script:
  - make -j4
  - packpack/packpack

branches:
  except:
    - legacy
notifications:
  recipients:
    - developers@moneymanagerex.org
  email:
    on_success: change
    on_failure: always
